### ISSUE TITLE
歌词名称似乎没有中文（还是英文）的问号

### ISSUE THREAD

**Issue by XuKaFy** [Ludoux/LrcHelper#11]

**Comment by ludoux** [comment]
应该是英文问号吧，因为文件名不能有问号，所以软件保存的时候就直接删去了
________________________________

**Comment by XuKaFy** [comment]
又核查了一下，是中文问号没了，比如说歌曲ID=1347247828

**Comment by ludoux** [comment]
![圖片](https://user-images.githubusercontent.com/13460812/70434012-12d0be80-1abe-11ea-92b8-f1d8ec145ad7.png)
这个歌曲好像是英文的吧……我手动粘贴过去重命名文件会报错的
