### ISSUE TITLE
可以增加选择保存文件编码的功能吗

### ISSUE THREAD

**Issue by ri-char** [Ludoux/LrcHelper#12]

**Comment by ludoux** [comment]
应该能，你想它提供什么编码？GB2312么

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: riChar <notifications@github.com>
发送时间: Tuesday, March 10, 2020 4:54:01 PM
收件人: ludoux/LrcHelper <LrcHelper@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ludoux/LrcHelper] 可以增加选择保存文件编码的功能吗 (#12)


―

**Comment by ri-char** [comment]
是的 我的mp3似乎不支持utf-8

**Comment by ludoux** [comment]
好，我这几天弄出来，到时候会回复这个issue的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: riChar <notifications@github.com>
发送时间: Tuesday, March 10, 2020 5:00:59 PM
收件人: ludoux/LrcHelper <LrcHelper@noreply.github.com>
抄送: Lu Chang <chinaluchang@live.com>; Comment <comment@noreply.github.com>
主题: Re: [ludoux/LrcHelper] 可以增加选择保存文件编码的功能吗 (#12)


是的 我的mp3似乎不支持utf-8

―

**Comment by ri-char** [comment]
十分感谢

**Comment by ludoux** [comment]
好了，v2.2.0，打开高级功能，编码选择GB2312或者输入别的都可以，然后点保存，下次程序运行的时候自动会加载。（log.txt 还是 UTF-8）

**Comment by ri-char** [comment]
可以了 感谢
