### ISSUE TITLE
希望能添加一个更改歌手分隔符的功能

### ISSUE THREAD

**Issue by 3301152539** [Ludoux/LrcHelper#13]
网易云中下载歌曲对于多个歌手的命名如下
歌手A 歌手B - 歌曲名
然而下载下来的歌词命名如下
歌手A,歌手B - 歌曲名
对不上啊(哭
批量重命名后又有一部分被错误改掉
难受至极

**Comment by ludoux** [comment]
[cid:image003.png@01D5FA0F.5F0D2C90]这个当初设计的时候有考虑的，麻烦给一下网易云版本号（是微软商店版本还是通用版），我这里下载下来的歌曲是,分割的啊
edit:
我这里是通用版2.7.1(198242)，下下来是逗号,分割的
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 3301152539 <notifications@github.com>
发送时间: Saturday, March 14, 2020 2:43:41 PM
收件人: ludoux/LrcHelper <LrcHelper@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ludoux/LrcHelper] 希望能添加一个更改歌手分隔符的功能 (#13)


网易云中下载歌曲对于多个歌手的命名如下
歌手A 歌手B - 歌曲名
然而下载下来的歌词命名如下
歌手A,歌手B - 歌曲名
对不上啊(哭
批量重命名后又有一部分被错误改掉
难受至极

―

**Comment by ludoux** [comment]
![Snipaste_2020-03-14_14-48-53](https://user-images.githubusercontent.com/13460812/76676961-a78a1180-6603-11ea-8735-6ffe47c76584.png)

**Comment by 3301152539** [comment]
是手机下载的，版本号7.1.0´_>`

**Comment by ludoux** [comment]
手机下载音乐再用电脑下载的歌词么😓，个人建议是用电脑客户端统一下。这个功能我先记下来，但不一定很快加（因为这个分割符定义死了…

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 3301152539<mailto:notifications@github.com>
发送时间: 2020年3月15日 10:11
收件人: ludoux/LrcHelper<mailto:LrcHelper@noreply.github.com>
抄送: Lu Chang<mailto:chinaluchang@live.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [ludoux/LrcHelper] 希望能添加一个更改歌手分隔符的功能 (#13)


是手机下载的，版本号7.1.0´_>`

**Comment by Initial-heart-1** [comment]
@ludoux 这个 Issue 的需求似乎已经满足，或许需要关闭这个 Issue。
