### ISSUE TITLE
自定义cookies以下载“我喜欢的音乐”等歌单中的歌词

### ISSUE THREAD

**Issue by Ovler-Young** [Ludoux/LrcHelper#15]
﻿感谢你为本项目的付出。

请先确保已经阅读过 [wiki](https://github.com/Ludoux/LrcHelper/wiki) 的有关内容。你的问题很可能已经有对应的指引。

请先确保已经在 [issues](https://github.com/ludoux/lrchelper/issues) 中搜索过类似的问题，你的问题很可能已经被提及，也有了你所满意的回应。

----

都做了吗？

那么，请借助如下指引，来帮助理清思绪，提供更加准确的信息，使问题得到更快的处理。

## 我想提一个不错的建议

大声说出来吧。最好能以”首先，接着，这时可以有……“的形式来描述此建议带来的操作上的改变。

（在这里填写）
首先，有些歌单可能存在并不想公开的情况，为此网易云有隐私歌单功能，也许可以通过自己通过cookies的方法获得里面的歌曲。还有“我喜欢的音乐”里面也是这样。所以希望增加这个自定义cookies来下载歌单中的歌词功能。

**Comment by ludoux** [comment]
部分请求也需要带 cookie 访问，近期修复
