### ISSUE TITLE
下载歌单ID抓取歌曲数量异常

### ISSUE THREAD

**Issue by OTaku9418** [Ludoux/LrcHelper#17]
﻿感谢你为本项目的付出。

请先确保已经阅读过 [wiki](https://github.com/Ludoux/LrcHelper/wiki) 的有关内容。你的问题很可能已经有对应的指引。

请先确保已经在 [issues](https://github.com/ludoux/lrchelper/issues) 中搜索过类似的问题，你的问题很可能已经被提及，也有了你所满意的回应。

----

都做了吗？

那么，请借助如下指引，来帮助理清思绪，提供更加准确的信息，使问题得到更快的处理。

## 我想反馈一个使用中的问题

1. 软件版本（右键-属性-详细信息-产品版本）是？：

2.2.0.0&2.2.1.0均有发生

2. 外界环境是？（系统版本（包括位数）/联网状态是否正常）：

Win10 21H1 64bit/联网正常

3. 是在下载某个 ID 时必然发生的吗？如果是请附上 ID ：

playlist?id=830208477

4. 如果上者不是，可否描述一下问题发生前你所做的事？（如何复现？）：

下载成功一次歌单ID

5. 所指的问题是什么？：

再次下载同一歌单ID只能抓取到一首歌，其它歌单则一首也抓不到，换版本还是一样

——————————————————————————————————————
2021/5/22：也许是网易云官方的限制？过了几个小时后再次下载是正常的

**Comment by OTaku9418** [comment]
这是log
————————————————————————————

PlaylistID:830208477
PlaylistName:
Count:3
Task Status:Finished


SongNum|SongID      |SongName                                          |SongAlbum                               |SongArtist                    |LrcSts         |ErrorInfo
1      |562594166   |サイサキ                                              |サイサキ                                    |Reol                          |EXISTED        |√


2021/5/22 3:25:43   Used Time:0.542sec
[re: Made by LrcHelper @ https://github.com/ludoux/lrchelper ]
[ve:2.2.1.0]
Enjoy music with lyrics now!(*^_^*)

**Comment by ludoux** [comment]
`curl https://music.163.com/api/v3/playlist/detail?id=830208477&c=[{%22id%22:%22830208477%22}]`
`{"code":20001,"message":"登录后才可查看","debugInfo":null,"data":null,"failData":null,"msg":"登录后才可查看"}`
和 #17 一样需求。

**Comment by ludoux** [comment]
fixed in https://github.com/ludoux/LrcHelper/commit/6754fde15163c44a5ff09136631b6b25b7ce400d
