### ISSUE TITLE
3.0.0 Release 版本似乎存在问题

### ISSUE THREAD

**Issue by Initial-heart-1** [Ludoux/LrcHelper#22]
未在多台设备上进行测试。
我在同一台机器上直接由 master 的最新源码编译了一份程序，正常运行。
而 Release 的版本在请求歌单时可能存在一些问题。
具体问题可能需要进一步分析来确定，也不排除设备故障，但基于重新编译后正确运行的现象，打开这个 issue。

**Comment by Initial-heart-1** [comment]
另，虽然不对题但因为不值当单开一个 issue，在这里提一下：首页挂的 Moonlib 链接似乎已经挂掉了，现在似乎会转到出售页面。

**Comment by ludoux** [comment]
谢谢，已经替换。好像是 GitHub Actions 打包出来的程序有点问题，我换成我本地打包的了。
那个引用博客问题我后续看看挂一个历史镜像吧，谢谢提醒。
