### ISSUE TITLE
关于歌词命名中歌手存在空格的问题

### ISSUE THREAD

**Issue by stevennight** [Ludoux/LrcHelper#3]
你好， 关于命名，以格式为“歌手 - 曲名”的方式命名（曲名 - 歌手的格式也一样。），貌似歌手中如果存在空格都会去掉，与网易云下载下来的文件命名不一。
比如http://music.163.com/song?id=34274786
V.A. 豊永利行 小野友樹 古川慎 村田太志 沢城千春 - さよなら並木道.mp3
V.A.豊永利行小野友樹古川慎村田太志沢城千春 - さよなら並木道.lrc

**Comment by ludoux** [comment]
没错，但我很长的时间里都维护不了了。除非自己改相关代码，只能自己改文件名了…十分抱歉??

会修改这个的原因是要过滤掉于文件路径中的非法字符，但是由于遇到的情况类型不多，软件修改的方式可能会和网易云修改的方式可能不一样。
________________________________

**Comment by stevennight** [comment]
好的。

**Comment by ludoux** [comment]
单纯 reopen 提醒自己有这个问题，并不是说要修复🤣，望理解～

**Comment by ludoux** [comment]
你好很抱歉打扰了，假如方便的话，请问现在这个软件最新版本(.11)还可以正常使用，出歌词文件么？因为现在有人反馈说有问题🤣

假如可以测试的话，若可以生成麻烦给一下 ID，不能且报错的话麻烦点开那个详细信息复制下错误信息谢谢～

**Comment by stevennight** [comment]
@ludoux 貌似确实出问题了
不过期间重装过这个系统，不知道是否有所变化，例如net. 版本。

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: i
   在 System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   在 ludoux.LrcHelper.NeteaseMusic.Music.fetchInfo()
   在 ludoux.LrcHelper.NeteaseMusic.Music.get_Title()
   在 ludoux.LrcHelper.FileWriter.LyricsFileWriter..ctor(String folderPath, String filenamePatern, Music music, String fileEncoding, Int32 totalWidth)
   在 LrcHelper.LrcDownloader.DownloadLrc(String folderPath, String filenamePatern, Music music, Int32 ModeIIndex, Int32 DelayMsc, LyricsStatus& status, String& filePath, String fileEncoding, String revisedsContentOriLyricsForUserReviseFunc, String revisedsContentTransLyricsForUserReviseFunc)
   在 LrcHelper.LrcDownloader.GETbutton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3101.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LrcHelper
    程序集版本:1.0.0.0
    Win32 版本:1.0.11.0
    基本代码:file:///C:/Users/Steve/Desktop/LrcHelper.exe
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3101.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

好像和隔壁的issue的是一样的。

**Comment by stevennight** [comment]
https://github.com/ludoux/LrcHelper/blob/49569287524ff09f32c4faba9dc388f95948ebe8/LrcHelper/NeteaseMusic.cs#L210
这里问题吗？
不是很懂C#也有点爱莫能助😭

**Comment by ludoux** [comment]
现在最新版本应该修复了，和网易云音乐桌面版一样，使用`,`来分隔不同的歌手。
