### ISSUE TITLE
我想反馈一个使用中的问题

### ISSUE THREAD

**Issue by SteveBlackHumor** [Ludoux/LrcHelper#4]
﻿感谢你为本项目的付出。

请先确保已经阅读过 [wiki](https://github.com/Ludoux/LrcHelper/wiki) 的有关内容。你的问题很可能已经有对应的指引。

请先确保已经在 [issues](https://github.com/ludoux/lrchelper/issues) 中搜索过类似的问题，你的问题很可能已经被提及，也有了你所满意的回应。

----

都做了吗？

那么，请借助如下指引，来帮助理清思绪，提供更加准确的信息，使问题得到更快的处理。

## 我想反馈一个使用中的问题

1. 软件版本（右键-属性-详细信息-产品版本）是？：

（在这里填写）

2. 外界环境是？（系统版本（包括位数）/联网状态是否正常）：

（在这里填写）

3. 是在下载某个 ID 时必然发生的吗？如果是请附上 ID ：

（在这里填写）

4. 如果上者不是，可否描述一下问题发生前你所做的事？（如何复现？）：

（在这里填写）

5. 所指的问题是什么？：

（在这里填写）

## 我想提一个不错的建议

大声说出来吧。最好能以”首先，接着，这时可以有……“的形式来描述此建议带来的操作上的改变。

（在这里填写）

## 我想指出一处不足之处

你可能是没有时间 pull requests，否则我建议你 pull requests 来在提交历史中留存着你的名字。

请直接指出代码某处的错误，（最好）以及对应的更正方法。我尽快处理并在 commit 中附上你的名字。

（在这里填写）

**Comment by SteveBlackHumor** [comment]
1.软件版本 1.0.11.0
4.将链接的id粘入，按下get，（操作应该没有问题）等了5分钟
5.按下之后，生成的文件夹里没有lrc文件，一个都没有

**Comment by ludoux** [comment]
你好，假如生成了文件夹的话，可以看一下里面有没有 log 文件，可以贴上来么？
是某一个 ID 特有的么？可以把整个链接发上来么？

我觉得可能是这个音乐没有歌词🤣

**Comment by ludoux** [comment]
#5
