### ISSUE TITLE
ArgumentOutOfRangeException: .FileWriter -> fetchInfo(), 无法生成歌词文件

### ISSUE THREAD

**Issue by SteveBlackHumor** [Ludoux/LrcHelper#5]
﻿## 我想反馈一个使用中的问题

1. 软件版本（右键-属性-详细信息-产品版本）是？：

  1.0.11.0

2. 外界环境是？（系统版本（包括位数）/联网状态是否正常）：

  64，正常

3. 是在下载某个 ID 时必然发生的吗？如果是请附上 ID ：

  不是

4. 如果上者不是，可否描述一下问题发生前你所做的事？（如何复现？）：

  粘贴了链接的id，按下了get

5. 所指的问题是什么？：

  按下get后等了5分钟，确实生成了正确的歌词文件夹，但里面没有歌词文件

**Comment by ludoux** [comment]
你好，假如生成了文件夹的话，可以看一下里面有没有 log 文件，可以贴上来么？

点击 Get 之后，软件右半边的 status 里面有什么信息可以截一下图么？

**Comment by SteveBlackHumor** [comment]
没有任何文件

**Comment by SteveBlackHumor** [comment]
截图请等一下

**Comment by SteveBlackHumor** [comment]
![2](https://user-images.githubusercontent.com/38856763/39426198-79132746-4cb1-11e8-9709-dc57b5e5c316.png)

**Comment by ludoux** [comment]
抱歉我好像不是特别明白，是“任何”的单曲专辑歌单都无法正常生成 lrc 文件么？填完 ID 后要单选一下正确的类型软件才可以正常工作。
只有选择了专辑或歌单类型，才会出文件夹，若给的是单曲，会直接在软件目录下生成歌词文件。

**Comment by SteveBlackHumor** [comment]
选了正确的类型，好像只是我喜欢的歌单没有办法生成，试了下其他的都没问题

**Comment by ludoux** [comment]
http://music.163.com/#/playlist/3236150/

可以试一下下载这个可不可以正常出来。
假如还是不可以的话，使用一下 reviseraw 功能把两次软件填写在剪贴板里的数据复制过来
主要是我现在没有电脑不能看…我不知道是不是网易那边接口改了

**Comment by SteveBlackHumor** [comment]
额，这个歌单也不行，同样只有文件夹

**Comment by ludoux** [comment]
不用 revise raw 先
请问可以单曲下载么？

**Comment by SteveBlackHumor** [comment]
单曲下载也没有在同级文件夹看到文件

**Comment by SteveBlackHumor** [comment]
没有用revise raw

**Comment by ludoux** [comment]
所以但现在是没有成功生成任何一首歌的歌词文件过么…

有没有可能是权限问题，尝试着将软件移到 D 盘再看看？

所以下单曲时，右边的 statusinfo 的文本也没有变过么？

假如上面都不行的话，下载一个有歌词的单曲，按 get 前开启 ReviseRaw ，分别两次将软件写到剪贴板的文本复制过来，不用清空剪贴板(可以看一下 wiki 里面的介绍)，我想看一看软件在联网获取网易云歌词时有没有问题，还是说获取成功了但没有办法写成文件。谢谢～

**Comment by SteveBlackHumor** [comment]
移到D盘也不行
右边的文本只是变成了finished，但没有文件

第一次

{"sgc":true,"sfy":false,"qfy":false,"transUser":{"id":28661564,"status":0,"demand":0,"userid":81810583,"nickname":"迪幻字幕组","uptime":1438143081356},"tlyric":{"version":5,"lyric":"[00:01.170]我怀念曾经的甜蜜日子\n[00:04.170]我怀念温柔的你侬我侬\n[00:08.170]今晚我只求情歌来疗伤\n[00:12.160]但怎么寻找都难寻佳音\n[00:16.150]曾经认为我们天造地设\n[00:20.040]共同描绘未来美好蓝图\n[00:24.030]但途中我不慎失败受困\n[00:28.020]可宝贝为何你要抛弃我\n[00:31.100]在你最黑暗的日子里我为你不离不弃\n[00:35.130]在你最忧郁的时光里我为你不离不弃\n[00:39.240]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[00:45.330]你不是说过会支持我的么 但如今  你又在哪\n[00:49.710]无论你如何选择离开  我都能发现你\n[00:53.290]沿着你的足迹  \n[00:56.830]我不懈追寻\n[00:58.630]追随你不止步\n[01:00.520]沿着你的足迹\n[01:02.210]紧紧追寻  不放弃希望\n[01:04.710]追随你不止步\n[01:06.660]克制不住自己\n[01:08.700]沿着你的足迹 \n[01:10.090]紧紧追寻  不放弃希望\n[01:12.340]梦里都是你的音容笑貌\n[01:16.070]诱惑总总让人难以自持\n[01:20.070]不知为何有种特别情愫\n[01:23.740]就是无法忘记你的身影\n[01:27.320]怎么做也无法忘记你啊\n[01:31.350]我为你不离不弃\n[01:33.190]在你最黑暗的日子里\n[01:35.130]在你最忧郁的时光里 我始终陪在你身边\n[01:39.070]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[01:45.240]你不是说过会支持我的么 但如今  你又在哪\n[01:49.630]无论你如何选择离开  我都能发现你\n[01:53.240]沿着你的足迹  我不懈追寻\n[01:56.620]追随你不止步\n[01:58.610]克制不住自己\n[02:00.550]沿着你的足迹 \n[02:02.110]紧紧追寻  不放弃希望\n[02:04.640]追随你不止步\n[02:06.680]克制不住自己\n[02:08.590]沿着你的足迹 \n[02:11.280]Oh oh oh\n[02:15.260]Yeah yeah yeah\n[02:17.200]Oh oh\n[02:19.110]Oh oh\n[02:20.350]我为你不离不弃\n[02:21.310]在你最黑暗的日子里\n[02:23.050]我始终陪在你身边\n[02:25.090]在你最忧郁的时光里\n[02:27.030]我为你不离不弃\n[02:29.020]在你最黑暗的日子里\n[02:30.810]我始终陪在你身边\n[02:33.050]在你最忧郁的时光里\n[02:34.890]但如今当我陷入人生低谷孤立无援的时候  你又在哪\n[02:41.280]你不是说过会支持我的么 但如今  你又在哪\n[02:45.360]无论你如何选择离开  我都能发现你\n[02:48.950]沿着你的足迹  我不懈追寻\n[02:52.330]追随你不止步\n[02:54.220]克制不住自己\n[02:56.470]沿着你的足迹  \n[02:57.810]紧紧追寻  不放弃希望\n[03:00.300]追随你不止步\n[03:02.190]克制不住自己\n[03:04.180]沿着你的足迹 \n[03:05.850]紧紧追寻  不放弃希望"},"code":200}

以上是一首英文歌...

第二次

{"sgc":true,"sfy":false,"qfy":false,"transUser":{"id":28661564,"status":0,"demand":0,"userid":81810583,"nickname":"迪幻字幕组","uptime":1438143081356},"tlyric":{"version":5,"lyric":"[00:01.170]我怀念曾经的甜蜜日子\n[00:04.170]我怀念温柔的你侬我侬\n[00:08.170]今晚我只求情歌来疗伤\n[00:12.160]但怎么寻找都难寻佳音\n[00:16.150]曾经认为我们天造地设\n[00:20.040]共同描绘未来美好蓝图\n[00:24.030]但途中我不慎失败受困\n[00:28.020]可宝贝为何你要抛弃我\n[00:31.100]在你最黑暗的日子里我为你不离不弃\n[00:35.130]在你最忧郁的时光里我为你不离不弃\n[00:39.240]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[00:45.330]你不是说过会支持我的么 但如今  你又在哪\n[00:49.710]无论你如何选择离开  我都能发现你\n[00:53.290]沿着你的足迹  \n[00:56.830]我不懈追寻\n[00:58.630]追随你不止步\n[01:00.520]沿着你的足迹\n[01:02.210]紧紧追寻  不放弃希望\n[01:04.710]追随你不止步\n[01:06.660]克制不住自己\n[01:08.700]沿着你的足迹 \n[01:10.090]紧紧追寻  不放弃希望\n[01:12.340]梦里都是你的音容笑貌\n[01:16.070]诱惑总总让人难以自持\n[01:20.070]不知为何有种特别情愫\n[01:23.740]就是无法忘记你的身影\n[01:27.320]怎么做也无法忘记你啊\n[01:31.350]我为你不离不弃\n[01:33.190]在你最黑暗的日子里\n[01:35.130]在你最忧郁的时光里 我始终陪在你身边\n[01:39.070]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[01:45.240]你不是说过会支持我的么 但如今  你又在哪\n[01:49.630]无论你如何选择离开  我都能发现你\n[01:53.240]沿着你的足迹  我不懈追寻\n[01:56.620]追随你不止步\n[01:58.610]克制不住自己\n[02:00.550]沿着你的足迹 \n[02:02.110]紧紧追寻  不放弃希望\n[02:04.640]追随你不止步\n[02:06.680]克制不住自己\n[02:08.590]沿着你的足迹 \n[02:11.280]Oh oh oh\n[02:15.260]Yeah yeah yeah\n[02:17.200]Oh oh\n[02:19.110]Oh oh\n[02:20.350]我为你不离不弃\n[02:21.310]在你最黑暗的日子里\n[02:23.050]我始终陪在你身边\n[02:25.090]在你最忧郁的时光里\n[02:27.030]我为你不离不弃\n[02:29.020]在你最黑暗的日子里\n[02:30.810]我始终陪在你身边\n[02:33.050]在你最忧郁的时光里\n[02:34.890]但如今当我陷入人生低谷孤立无援的时候  你又在哪\n[02:41.280]你不是说过会支持我的么 但如今  你又在哪\n[02:45.360]无论你如何选择离开  我都能发现你\n[02:48.950]沿着你的足迹  我不懈追寻\n[02:52.330]追随你不止步\n[02:54.220]克制不住自己\n[02:56.470]沿着你的足迹  \n[02:57.810]紧紧追寻  不放弃希望\n[03:00.300]追随你不止步\n[03:02.190]克制不住自己\n[03:04.180]沿着你的足迹 \n[03:05.850]紧紧追寻  不放弃希望"},"code":200}

**Comment by SteveBlackHumor** [comment]
这次单曲下载直接这样。。。
![3](https://user-images.githubusercontent.com/38856763/39427486-7ce9adf4-4cb6-11e8-8add-3908bdfdedfc.png)

**Comment by SteveBlackHumor** [comment]
如果你不方便，可以以后再处理的

**Comment by ludoux** [comment]
好奇怪我之前都没有遇到过…

那个 Revise raw 两次出来的文本不应该一样啊🤣可以再试一次么…在弹出第一次窗口后把内容粘贴过来，然后再点击弹窗继续，弹出第二个窗口后再粘贴一次，再点弹窗继续

后面假如还有出那个错误框，麻烦点一些那个详细信息然后把里面的文本全部复制过来谢谢～

我短期没有机会碰电脑，过几天我上机看看我这边能不能正常出来歌词文件…

软件出 Bug 抱歉啦，也谢谢你这一个多小时的帮助。希望最后能解决

**Comment by ludoux** [comment]
假如你还对这个软件抱有希望的话…可以尝试一个一个下载一下历史版本，说不定哪个就能动了🤣

**Comment by SteveBlackHumor** [comment]
有希望，作者大大别放弃，等我再试一下你说的

**Comment by SteveBlackHumor** [comment]
详细信息：

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: i
   在 System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   在 ludoux.LrcHelper.NeteaseMusic.Music.fetchInfo()
   在 ludoux.LrcHelper.NeteaseMusic.Music.get_Title()
   在 ludoux.LrcHelper.FileWriter.LyricsFileWriter..ctor(String folderPath, String filenamePatern, Music music, String fileEncoding, Int32 totalWidth)
   在 LrcHelper.LrcDownloader.DownloadLrc(String folderPath, String filenamePatern, Music music, Int32 ModeIIndex, Int32 DelayMsc, LyricsStatus& status, String& filePath, String fileEncoding, String revisedsContentOriLyricsForUserReviseFunc, String revisedsContentTransLyricsForUserReviseFunc)
   在 LrcHelper.LrcDownloader.GETbutton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.2633.0 built by: NET471REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LrcHelper
    程序集版本:1.0.0.0
    Win32 版本:1.0.11.0
    基本代码:file:///C:/Users/%E8%83%A1%E8%89%BE%E9%A2%A2%E9%98%B3/Downloads/LrcHelper.exe
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.2633.0 built by: NET471REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.2612.0 built by: NET471REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2556.0 built by: NET471REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

第一次：
{"songStatus":3,"lyricVersion":30,"lyric":"[00:01.170]I miss the taste of a sweeter life\n[00:04.170]I miss the conversation\n[00:08.170]I’m searching for a song tonight\n[00:12.160]I’m changing all of the stations\n[00:16.150]I like to think that we had it all\n[00:20.040]We drew a map to a better place\n[00:24.030]But on that road I took a fall\n[00:28.020]Oh baby why did you run away\n[00:31.100]I was there for you in your darkest times\n[00:35.130]I was there for you in your darkest nights\n[00:39.240]But I wonder where were you when I was at my worst down on my knees\n[00:45.330]And you said you had my back so I wonder where were you\n[00:49.710]When all the roads you took came back to me\n[00:53.290]So I’m following the map that leads to you\n[00:56.830]The map that leads to you\n[00:58.630]ain't nothing I can do\n[01:00.520]The map that leads to you\n[01:02.210]Following, following, following to you\n[01:04.710]The map that leads to you\n[01:06.660]ain't nothing I can do\n[01:08.700]The map that leads to you\n[01:10.090]Following, following, following\n[01:12.340]I hear your voice in my sleep at night\n[01:16.070]Hard to resist temptation\n[01:20.070]Cause something strange has come over me\n[01:23.740]And now I can’t get over you\n[01:27.320]No I just can’t get over you\n[01:31.350]I was there for you\n[01:33.190]In your darkest times\n[01:35.130]I was there for you in your darkest times\n[01:39.070]But I wonder where were you when I was at my worst down on my knees\n[01:45.240]And you said you had my back so I wonder where were you\n[01:49.630]When all the roads you took came back to me\n[01:53.240]So I’m following the map that leads to you\n[01:56.620]The map that leads to you\n[01:58.610]ain't nothing I can do\n[02:00.550]The map that leads to you\n[02:02.110]Following, following, following to you\n[02:04.640]The map that leads to you\n[02:06.680]And nothing I can do\n[02:08.590]The map that leads to you\n[02:11.280]Oh oh oh\n[02:15.260]Yeah yeah yeah\n[02:17.200]Oh oh\n[02:19.110]Oh oh\n[02:20.350]Oh I was there for you\n[02:21.310]Oh In you darkest times\n[02:23.050]Oh I was there for you\n[02:25.090]Oh In your darkest nights\n[02:27.030]Oh I was there for you\n[02:29.020]Oh In you darkest times\n[02:30.810]Oh I was there for you\n[02:33.050]Oh In your darkest nights\n[02:34.890]But I wonder where were you when I was at my worst down on my knees\n[02:41.280]And you said you had my back so I wonder where were you\n[02:45.360]When all the roads you took came back to me\n[02:48.950]So I’m following the map that leads to you\n[02:52.330]The map that leads to you\n[02:54.220]ain't nothing I can do\n[02:56.470]The map that leads to you\n[02:57.810]Following, following, following to you\n[03:00.300]The map that leads to you\n[03:02.190]ain't nothing I can do\n[03:04.180]The map that leads to you\n[03:05.850]Following, following, following\n","code":200}

第二次：

{"sgc":true,"sfy":false,"qfy":false,"transUser":{"id":28661564,"status":0,"demand":0,"userid":81810583,"nickname":"迪幻字幕组","uptime":1438143081356},"tlyric":{"version":5,"lyric":"[00:01.170]我怀念曾经的甜蜜日子\n[00:04.170]我怀念温柔的你侬我侬\n[00:08.170]今晚我只求情歌来疗伤\n[00:12.160]但怎么寻找都难寻佳音\n[00:16.150]曾经认为我们天造地设\n[00:20.040]共同描绘未来美好蓝图\n[00:24.030]但途中我不慎失败受困\n[00:28.020]可宝贝为何你要抛弃我\n[00:31.100]在你最黑暗的日子里我为你不离不弃\n[00:35.130]在你最忧郁的时光里我为你不离不弃\n[00:39.240]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[00:45.330]你不是说过会支持我的么 但如今  你又在哪\n[00:49.710]无论你如何选择离开  我都能发现你\n[00:53.290]沿着你的足迹  \n[00:56.830]我不懈追寻\n[00:58.630]追随你不止步\n[01:00.520]沿着你的足迹\n[01:02.210]紧紧追寻  不放弃希望\n[01:04.710]追随你不止步\n[01:06.660]克制不住自己\n[01:08.700]沿着你的足迹 \n[01:10.090]紧紧追寻  不放弃希望\n[01:12.340]梦里都是你的音容笑貌\n[01:16.070]诱惑总总让人难以自持\n[01:20.070]不知为何有种特别情愫\n[01:23.740]就是无法忘记你的身影\n[01:27.320]怎么做也无法忘记你啊\n[01:31.350]我为你不离不弃\n[01:33.190]在你最黑暗的日子里\n[01:35.130]在你最忧郁的时光里 我始终陪在你身边\n[01:39.070]但如今当我陷入人生低谷 孤立无援的时候  你又在哪\n[01:45.240]你不是说过会支持我的么 但如今  你又在哪\n[01:49.630]无论你如何选择离开  我都能发现你\n[01:53.240]沿着你的足迹  我不懈追寻\n[01:56.620]追随你不止步\n[01:58.610]克制不住自己\n[02:00.550]沿着你的足迹 \n[02:02.110]紧紧追寻  不放弃希望\n[02:04.640]追随你不止步\n[02:06.680]克制不住自己\n[02:08.590]沿着你的足迹 \n[02:11.280]Oh oh oh\n[02:15.260]Yeah yeah yeah\n[02:17.200]Oh oh\n[02:19.110]Oh oh\n[02:20.350]我为你不离不弃\n[02:21.310]在你最黑暗的日子里\n[02:23.050]我始终陪在你身边\n[02:25.090]在你最忧郁的时光里\n[02:27.030]我为你不离不弃\n[02:29.020]在你最黑暗的日子里\n[02:30.810]我始终陪在你身边\n[02:33.050]在你最忧郁的时光里\n[02:34.890]但如今当我陷入人生低谷孤立无援的时候  你又在哪\n[02:41.280]你不是说过会支持我的么 但如今  你又在哪\n[02:45.360]无论你如何选择离开  我都能发现你\n[02:48.950]沿着你的足迹  我不懈追寻\n[02:52.330]追随你不止步\n[02:54.220]克制不住自己\n[02:56.470]沿着你的足迹  \n[02:57.810]紧紧追寻  不放弃希望\n[03:00.300]追随你不止步\n[03:02.190]克制不住自己\n[03:04.180]沿着你的足迹 \n[03:05.850]紧紧追寻  不放弃希望"},"code":200}

**Comment by SteveBlackHumor** [comment]
这次好像获取歌词没有问题

**Comment by SteveBlackHumor** [comment]
但是没有文件生成

**Comment by SteveBlackHumor** [comment]
作者大大，如果你不方便就去休息吧，可以以后处理的，已经非常谢谢你了

**Comment by ludoux** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
   at System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   at Ludoux.LrcHelper.NeteaseMusic.Music.fetchInfo()
   at Ludoux.LrcHelper.NeteaseMusic.Music.get_Title()
   at Ludoux.LrcHelper.FileWriter.LyricsFileWriter..ctor(String folderPath, String filenamePatern, Music music, String fileEncoding, Int32 totalWidth)
   at LrcHelper.LrcDownloader.DownloadLrc(String folderPath, String filenamePatern, Music music, Int32 ModeIIndex, Int32 DelayMsc, LyricsStatus& status, String& filePath, String fileEncoding)
   at LrcHelper.LrcDownloader.GETbutton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LrcHelper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.9.0
    CodeBase: file:///C:/LrcHelper.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
--------------------------

**Comment by ludoux** [comment]
我的朋友也是一样的结果…这个可能真的是 bug…

**Comment by ludoux** [comment]
你们都是 4.0 的环境(修正：4.7)
假如方便，可以试试下载下这个 https://www.microsoft.com/zh-CN/download/details.aspx?id=53344，装一下更新再试试么

你是知乎来的是吧，我改一下回答不要让人跳坑🤣

**Comment by ludoux** [comment]
https://www.microsoft.com/zh-cn/download/details.aspx?id=53345
请下这个在线更新包，不用下上面那个离线的，谢谢～

**Comment by SteveBlackHumor** [comment]
是知乎来的。

**Comment by SteveBlackHumor** [comment]
“这台计算机中已经安装了 .NET Framework 4.6.2 或版本更高的更新。”
额，我是个C语言小白，好像在 VS2017 里装过这东西。但显示是4.0环境，不知道为什么

**Comment by SteveBlackHumor** [comment]
要不明天再说吧，我有点困了。没有歌词也可以的，总之谢谢作者大大，非常认真负责、一丝不苟（不愧是做IT的人）

**Comment by ludoux** [comment]
抱歉了晚安～
你的版本是 Win32 版本:4.7.2633.0，我看错字段了…
我有可能修不了…我过几天上机看看能不能用
我朋友是.7 .9 .11 都和你一样报错
看错误信息的话，它具体是写文件时在获取歌词Title的时候崩掉了，正则没有匹配上还是怎样

**Comment by SteveBlackHumor** [comment]
很感谢作者大大，晚安~

**Comment by ludoux** [comment]
假如方便的话，可以用最新的.11 试一下 music
34274786
28151022
么？
(补充：我朋友帮我测了下，这几个也会出问题，但我之前的确是成功下载过的…不知道是不是外部问题比如网络什么的，或者是请求频率过高网易那边加强了限制？)

我没有电脑调试不了，这两个是我之前能下载成功的。针对 Maps 这首歌我手动匹配了一下正则好像没有问题🤣(但软件报错)

由于各种原因我可能要 **明年** 才能真机调试来修…假如你只是要下歌词别的软件也是 OK
的

**Comment by SteveBlackHumor** [comment]
抱歉，上午有事没看到，我来试一下

**Comment by SteveBlackHumor** [comment]
这两首歌也会报错（应用程序中出现了未经处理的异常）但是试了下reviseraw剪贴板里的歌词没有问题，应该是写入文件的问题吧

**Comment by ludoux** [comment]
是的。写入操作中需要访问网易云的另一个 API 地址来获取 title 和 artist 来确认歌词文件名，其中会用到正则表达式来匹配字段，这个过程崩掉了(之前没有遇到过所以也没有容错处理)。我不知道是软件没办法访问到网页(比如被特征反制了无法访问)还是说正则规则写的有问题。

主要是起码 30 天前有人提 issue，起码那个时候还是可以正常用的。这期间软件是没有什么变化的。

Edit: 那个 API 地址类似于 https://music.163.com/api/song/detail/?id=426881487&ids=[426881487] ，可以看看能不能在浏览器中正常打开(能也不意味着软件可以访问到，比如网易云可能拦截掉软件的访问)
________________________________

**Comment by SteveBlackHumor** [comment]
可以打开。剩下的我就不是很清楚了，很抱歉不能帮上什么忙

**Comment by ludoux** [comment]
只能我有机会时再处理了…很抱歉
这个 Issue 继续 open 着吧

**Comment by stevennight** [comment]
sContent 是"{\"code\":-460,\"msg\":\"Cheating\"}"

尝试注释这两句貌似反而能正常获取：
https://github.com/ludoux/LrcHelper/blob/49569287524ff09f32c4faba9dc388f95948ebe8/LrcHelper/NeteaseMusic.cs#L22
https://github.com/ludoux/LrcHelper/blob/49569287524ff09f32c4faba9dc388f95948ebe8/LrcHelper/NeteaseMusic.cs#L23

会不会会网易云的API防盗规则作了修改...😀

**Comment by stevennight** [comment]
😭 貌似还有另外的问题，id 2220626666 貌似某个值太大了Int32存不下来...(应该是这个id值？其他小的ID没事。)233
@ludoux 不过还是感谢作者。

**Comment by ludoux** [comment]
在 @stevennight 的热心帮助下，最新版本（v1.0.12）已经修复了。先看看情况再关 issue.
特别感谢 @stevennight ！

**Comment by ludoux** [comment]
测了个 400+ 的英文歌单，均成功生成。
