### ISSUE TITLE
歌单超过一千首歌就只会扫描前一千首歌

### ISSUE THREAD

**Issue by XuKaFy** [Ludoux/LrcHelper#8]

**Comment by ludoux** [comment]
那我可能要改 api 了，我下个月初研究一下。到时候假如能解决我就直接推新版本出来。

**Comment by ludoux** [comment]
应该可以了，我用 `https://music.163.com/playlist?id=799680399` 这个测试的。
可以点一个 Star 么😜

**Comment by XuKaFy** [comment]
拿自己的歌单测试了，可以。
那必 Star 😜
