### ISSUE TITLE
我想反馈一个未能使用的问题

### ISSUE THREAD

**Issue by vcup** [Ludoux/LrcHelper#9]
## 我想反馈一个关于我未能使用的问题

1. 软件版本是？：

（v2.1.1）

2. 外界环境是？（系统版本（包括位数）/联网状态是否正常）：

（Windows 7 旗舰版 64-bit SP1）

3. 是在下载某个 ID 时必然发生的吗？如果是请附上 ID ：

（我还没能体验到贵软件的功能）

4. 如果上者不是，可否描述一下问题发生前你所做的事？（如何复现？）：

（打开163lrc.exe 稍后几秒弹出窗口 "163lrc已停止工作"）

5. 所指的问题是什么？：

（停止工作的问题）

.NET重装了好多次 版本是4.7.2 不管怎样做 打开之后就弹出停止工作
wiki和其他问题都查看了 没能找到可能的原因

![19-8-10_1_8_41_001](https://user-images.githubusercontent.com/53596976/62796096-e3f40d00-bb0a-11e9-87b4-8bc625f8ebd3.png)

**Comment by ludoux** [comment]
我调到 .Net Framework 4.5了，你看一下能不能运行。 https://github.com/ludoux/LrcHelper/releases/download/v2.1.1/dotnet4.5.7z
之前某一个版本之后，我在 Win7 上也无法运行了，不过后面全部升级到 Win10 我就没有管这个问题了😂

**Comment by vcup** [comment]
还是不能 是需要我换一下.NET的版本么

**Comment by ludoux** [comment]
那我也不知道了，其实我建议你换 Win10😂

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ｖCup <notifications@github.com>
发送时间: Saturday, August 10, 2019 10:42:21 AM
收件人: ludoux/LrcHelper <LrcHelper@noreply.github.com>
抄送: Lu Chang <chinaluchang@live.com>; Comment <comment@noreply.github.com>
主题: Re: [ludoux/LrcHelper] 我想反馈一个未能使用的问题 (#9)


还是不能 是需要我换一下.NET的版本么

**Comment by vcup** [comment]
电脑硬件太低级 装不了win10

**Comment by vcup** [comment]
也没钱再买电脑了

**Comment by ludoux** [comment]
那真的抱歉了，我之前也修过这个 bug 但是也没弄好😂

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ｖCup <notifications@github.com>
发送时间: Saturday, August 10, 2019 10:45:42 AM
收件人: ludoux/LrcHelper <LrcHelper@noreply.github.com>
抄送: Lu Chang <chinaluchang@live.com>; Comment <comment@noreply.github.com>
主题: Re: [ludoux/LrcHelper] 我想反馈一个未能使用的问题 (#9)


电脑硬件太低级 装不了win10

**Comment by vcup** [comment]
没事 我试试其他版本 如果找到可以用的我再来

**Comment by vcup** [comment]
LrcHelper.v1.0.5和1.0.5以下的版本正常打开
.NET4.7.2脱机包

**Comment by ludoux** [comment]
但旧的功能已经不能用了，然后新版本我也看不出来我改了什么…就突然不能用了…
________________________________

**Comment by vcup** [comment]
是 到1.0.5就突然能用了(不是)

**Comment by ludoux** [comment]
但是旧的版本里面的 UA 被网易封禁了，所以旧版本是下不了歌词的…
________________________________

**Comment by ludoux** [comment]
你好，时隔多年的回复，现在有一个 Qt 版本你可以去 releases 那边看一下，不过可能下载下来的中文文件名编码会有问题😅

**Comment by vcup** [comment]
> 你好，时隔多年的回复，现在有一个 Qt 版本你可以去 releases 那边看一下，不过可能下载下来的中文文件名编码会有问题😅

同样是时隔多年的回复，当时的硬件已经没有再用了，因此复现不了问题😂😊😊
